version: "3.8"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: jhuma23
      MARIADB_DATABASE: estudiantes_itm
      MARIADB_USER: root
      MARIADB_PASSWORD: jhuma23
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - net-app

  adminer:
    image: adminer:latest
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: always
    ports:
      - 8080:8080
    networks:
      - net-app
      
  web:
    build: .
    command: >
      bash -c "python manage.py migrate
      && python manage.py initadmin
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    depends_on:
      - mariadb
    networks:
      - net-app


networks:
  net-app:
    driver: bridge

volumes:
  db_data:
  