# Generated by Django 4.2.1 on 2023-06-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.PositiveBigIntegerField()),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.CharField(max_length=20)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=200)),
                ('barrio', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('estrato', models.CharField(max_length=200)),
                ('dir_latitude', models.CharField(max_length=200)),
                ('dir_longitude', models.CharField(max_length=200)),
                ('carrera', models.CharField(max_length=200)),
                ('facultad', models.CharField(max_length=200)),
                ('creditos_aprobados', models.PositiveBigIntegerField()),
                ('promedio_acumulado', models.FloatField()),
            ],
        ),
    ]
